/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package happyfrog;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author tuannnh
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    GameScreen gameScreen;
    private boolean isRunning, isAlive;

    public MainWindow() {
        isRunning = false;
        isAlive = false;
        initComponents();
        gameScreen = new happyfrog.GameScreen(btnStart, lblPoint);
        gameScreen.setPreferredSize(new Dimension(500, 350));
        gamePanel.setVisible(true);
        gamePanel.add(gameScreen);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPoint = new javax.swing.JLabel();
        gamePanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        headerPanel.setPreferredSize(new java.awt.Dimension(500, 50));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Points:");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        lblPoint.setText("0");
        headerPanel.add(lblPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        gamePanel.setBackground(new java.awt.Color(102, 204, 255));
        gamePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 255), null));
        gamePanel.setPreferredSize(new java.awt.Dimension(500, 350));
        gamePanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(gamePanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setPreferredSize(new java.awt.Dimension(500, 140));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setText("New Game");
        btnNew.setPreferredSize(new java.awt.Dimension(130, 40));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        buttonPanel.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnStart.setText("Start");
        btnStart.setPreferredSize(new java.awt.Dimension(130, 40));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        buttonPanel.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btnSave.setText("Save");
        btnSave.setPreferredSize(new java.awt.Dimension(130, 40));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        buttonPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        btnLoad.setText("Load");
        btnLoad.setPreferredSize(new java.awt.Dimension(130, 40));
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        buttonPanel.add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnExit.setText("Exit");
        btnExit.setPreferredSize(new java.awt.Dimension(130, 40));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        gameScreen.createNewGame();
        btnStart.setText("Start");

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        //If game not running, start the game
        //Game is not started
        if (btnStart.getText().equalsIgnoreCase("Start")) {
            //Start game
            //Change Start button text to Pause
            btnStart.setText("Pause");
        } //Game is started and running
        else if (btnStart.getText().equalsIgnoreCase("Pause")) {
            //Pause the game
            //Change Start button text to Resume
            btnStart.setText("Resume");
        } //Game is started but pausing
        else {
            //Change Start button text to Pause
            btnStart.setText("Pause");
        }
        gameScreen.requestFocus();

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        gameScreen.saveGame();
        btnStart.setText("Resume");
        JOptionPane.showMessageDialog(this, "Game saved");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        btnStart.setText("Resume");
        gameScreen.loadGame();
    }//GEN-LAST:event_btnLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPoint;
    // End of variables declaration//GEN-END:variables
}
